### ISSUE TITLE
ImportError after install

### ISSUE THREAD

**Issue by schoeller** [SWMM-Project/swmm-python#2]
Dear all,

I have installed cmake on Ubuntu Focal and the from source
1#https://scikit-build.readthedocs.io/en/latest/installation.html#install-from-source
2#https://github.com/SWMM-Project/swmm-python/releases/download/v0.6.0-rc.1/swmm-toolkit-0.5.0.tar.gz
When calling from python console manually I still run into this error:
```
>>> from swmm.toolkit import solver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/solver.py", line 13, in <module>
    from . import _solver
ImportError: libswmm5.so: cannot open shared object file: No such file or directory
```
I would be grateful for any hints on how to advance.

Kind regards

Sebastian

**Comment by michaeltryby** [comment]
@schoeller What command did you use to build and install the package? 

The sdist for `swmm-toolkit` contains the source code for libswmm5.so. I'm guessing that it didn't get built or got installed in an unanticipated place. 

Assuming you have dependencies installed you should be able to run the following:
```
% cd swmm-toolkit
% python setup.py bdist_wheel
% pip install dist/swmm_toolkit-0.5.0-py3.8-linux-x86_64.whl
```
I've tested on Ubuntu Python 3.7 so this should work for you!

**Comment by michaeltryby** [comment]
Alternately, you can run
```
$ pip install swmm-toolkit-0.5.0.tar.gz
```

**Comment by schoeller** [comment]
> @schoeller What command did you use to build and install the package?
> 
> The sdist for `swmm-toolkit` contains the source code for libswmm5.so. I'm guessing that it didn't get built or got installed in an unanticipated place.
> 
> Assuming you have dependencies installed you should be able to run the following:
> 
> ```
> % cd swmm-toolkit
> % python setup.py bdist_wheel
> % pip install dist/swmm_toolkit-0.5.0-py3.8-linux-x86_64.whl
> ```
> 
> I've tested on Ubuntu Python 3.7 so this should work for you!

@michaeltryby 
I installed using
`% python setup.py install`
Now the egg lives underneath `/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg` with the following contents
```
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/output_enum.py
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/_solver.cpython-38-x86_64-linux-gnu.so
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/__pycache__
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/__pycache__/output_enum.cpython-38.pyc
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/__pycache__/output_metadata.cpython-38.pyc
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/__pycache__/__init__.cpython-38.pyc
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/__pycache__/output.cpython-38.pyc
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/__pycache__/solver.cpython-38.pyc
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/output.py
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/_output.cpython-38-x86_64-linux-gnu.so
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/__init__.py
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/solver.py
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/output_metadata.py
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/lib
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/lib/libswmm-output.so
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/lib/libswmm5.so
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/EGG-INFO
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/EGG-INFO/not-zip-safe
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/EGG-INFO/SOURCES.txt
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/EGG-INFO/native_libs.txt
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/EGG-INFO/PKG-INFO
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/EGG-INFO/requires.txt
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/EGG-INFO/dependency_links.txt
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/EGG-INFO/top_level.txt
```
So the library has been compiled and installed indeed. When calling the path from python is says
```
>>> for path in sys.path:
...     print(path)
... 

/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/sebastian/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/local/lib/python3.8/dist-packages/swmm_output-0.1.0a0-py3.8-linux-x86_64.egg
/usr/local/lib/python3.8/dist-packages/enum34-1.1.10-py3.8.egg
/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg
/usr/lib/python3/dist-packages
/usr/lib/python3.8/dist-packages
```
I have linked the library manually doing
```
% sudo ln -s /usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/lib/libswmm5.so /usr/local/lib/
% sudo ldconfig
```
Loading from python command using `from swmm.toolkit import solver` now works. Don't know how to resolve the issue more elegantly.

**Comment by schoeller** [comment]
@michaeltryby 
When trying to compile SWMM-EPANET GUI I run into a new error `ModuleNotFoundError: No module named 'swmm.output'`. When manually linking as follows
```
% sudo ln -s /usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/lib/libswmm-output.so /usr/local/lib/
% sudo ldconfig
```
I get an error on the python command line
```
>>> from swmm.output import output as _lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'swmm.output'
>>>
```
Any hints?

**Comment by michaeltryby** [comment]
@schoeller I don't have Ubuntu Focal or Python 3.8 set up at the moment.  Can you help me by doing a small test on your machine? 

Can you build and install the wheel by running the commands I sent instead of installing it as an egg. I'm curious if that will work for you. Thanks!

**Comment by schoeller** [comment]
@michaeltryby 
After deinstalling the egg I recompiled using bdist_wheel as recommended and installed
```
pip3 install dist/swmm_toolkit-0.5.0-cp38-cp38-linux_x86_64.whl 
Processing ./dist/swmm_toolkit-0.5.0-cp38-cp38-linux_x86_64.whl
Requirement already satisfied: aenum in /home/sebastian/.local/lib/python3.8/site-packages (from swmm-toolkit==0.5.0) (2.2.3)
Installing collected packages: swmm-toolkit
Successfully installed swmm-toolkit-0.5.0
```
I do not have to link the library manually any longer, so that's a bonus and importing swmm.toolkit from python works (`from swmm.toolkit import solver`), but the other import still throws an error
```
>>> from swmm.output import output as _lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'swmm.output'
```

**Comment by michaeltryby** [comment]
Great! The UI code needs to be refactored to use the updated `swmm-toolkit` package.  The import statement should be `from swmm.toolkit import output`.  Many other changes are going to be necessary as well.

**Comment by schoeller** [comment]
@michaeltryby 
```
>>> from swmm.toolkit import output as _lib
>>> dir(_lib)
['MAXELENAME', 'MAXFILENAME', '_SwigNonDynamicMeta', '__builtin__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_output', '_swig_add_metaclass', '_swig_python_version_info', '_swig_repr', '_swig_setattr_nondynamic_class_variable', '_swig_setattr_nondynamic_instance_variable', 'close', 'get_elem_name', 'get_link_attribute', 'get_link_result', 'get_link_series', 'get_node_attribute', 'get_node_result', 'get_node_series', 'get_proj_size', 'get_start_date', 'get_subcatch_attribute', 'get_subcatch_result', 'get_subcatch_series', 'get_system_attribute', 'get_system_result', 'get_system_series', 'get_times', 'get_units', 'get_version', 'init', 'open']
```
What would be the right way to contribute to this?

**Comment by michaeltryby** [comment]
@schoeller fell free to contact me via email to discuss. Thanks!
